apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: eksclusters.aws.hops.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: aws.hops.ops.com.ai/v1alpha1
    kind: EKSCluster
  mode: Pipeline
  pipeline:
  - step: render
    functionRef:
      name: hops-ops-aws-eks-clusterrender
  - step: crossplane-contrib-function-auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
